### ISSUE TITLE
Compatibility with `batoms` v2.2.0

### ISSUE THREAD

**Issue by alchem0x2A** [beautiful-atoms/beautiful-atoms-api#8]
We should fix the compatibility with `batoms` v2.2.0 in the upcoming version `0.2.2` of `batoms_api`.
- [x] Remove obsolete properties keywords
- [x] Additional setting for `batoms.cell`
- [ ]~Merge batoms_input and render_input with general settings~
- [x] More testing with polyhedras / lattice_planes / crystal_shape

**Comment by superstar54** [comment]
Since there is a big update and will have a different design (#7 ) for `batoms_api`, I suggest the upcoming version be 1.0.0.

**Comment by alchem0x2A** [comment]
For now I'll make `batoms_api` version `0.2.x` incremental implementation of minor feature before bumping to `1.0.0` with the new rendering logic. Version 0.2.2 will be mainly compatibility enhancement with batoms v2.2.0 and still keep parameters like `batoms_input` and `render_input`. Will close this issue and track the newer design in other issues.
